// One-time migration: pull the current Firebase tierlist + likes, extract every
// embedded base64 image to tools/out/images/<sha1>.<ext>, rewrite values to URLs,
// and emit a cleaned JSON + an import.sql for the new MySQL DB.
//
// Run: node tools/migrate.mjs
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FB = 'https://nexus-117f0-default-rtdb.europe-west1.firebasedatabase.app';
const OUT = join('tools', 'out');
const IMG = join(OUT, 'images');
mkdirSync(IMG, { recursive: true });

function extFromMeta(meta) {
  if (meta.includes('image/webp')) return 'webp';
  if (meta.includes('image/jpeg') || meta.includes('image/jpg')) return 'jpg';
  return 'png';
}

function saveDataUrl(dataUrl) {
  const comma = dataUrl.indexOf(',');
  const meta = dataUrl.slice(5, comma);
  const bytes = Buffer.from(dataUrl.slice(comma + 1), 'base64');
  const ext = extFromMeta(meta);
  const name = createHash('sha1').update(bytes).digest('hex') + '.' + ext;
  writeFileSync(join(IMG, name), bytes);
  return '/images/' + name;
}

function rewrite(val) {
  return (typeof val === 'string' && val.startsWith('data:')) ? saveDataUrl(val) : val;
}

const [tRes, lRes] = await Promise.all([
  fetch(`${FB}/tierlist.json`),
  fetch(`${FB}/likes.json`),
]);
const state = await tRes.json();
const likesRaw = await lRes.json();
const likes = (typeof likesRaw === 'number' && likesRaw >= 0) ? likesRaw : 0;

let imgCount = 0;
const countingRewrite = (v) => { const out = rewrite(v); if (out !== v) imgCount++; return out; };

for (const tier of (state.tiers || [])) {
  if (tier.logo) tier.logo = countingRewrite(tier.logo);
  for (const item of (tier.items || [])) {
    if (item.icon) item.icon = countingRewrite(item.icon);
  }
}
if (state.ad && state.ad.image) state.ad.image = countingRewrite(state.ad.image);

const rev = 1;
state._rev = rev;
const clean = JSON.stringify(state);
writeFileSync(join(OUT, 'tierlist.clean.json'), clean);

// Emit import.sql. Escape single quotes and backslashes for a MySQL string literal.
const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const sql = [
  '-- Generated by tools/migrate.mjs. Run after schema.sql.',
  `UPDATE tierlist SET data = '${esc(clean)}', rev = ${rev} WHERE id = 1;`,
  `UPDATE likes SET count = ${likes} WHERE id = 1;`,
  '',
].join('\n');
writeFileSync(join(OUT, 'import.sql'), sql);

console.log(`images extracted: ${imgCount}`);
console.log(`clean json bytes: ${clean.length}`);
console.log(`likes: ${likes}`);
console.log(`outputs in ${OUT}/ (images/, tierlist.clean.json, import.sql)`);
